STRINGS = GLOBAL.STRINGS

STRINGS.FORBIDDEN_LOADINGTIPS = {
    "Winbot places items on the go inside dropped backpacks as Winona.",
    "Winbot scares grass geckos like chester, and also picks up the grass.",
    "Cookie cutters are distracted towards wood items in the water (log suits, woodie hats, etc).",
    "Dark swords and shadow monsters like shadow merms keep gestlats away on lunar island.",
    "Moles dont steal socketed moonlens, so you can mark wormholes for everyone to see.",
    "Webber switcherdoodles are non-spoil -10 sanity for other characters that need it, like Willow.",
    "Non-spoil Eyemask restoration: Kitcshy idols (Woodie), Syrup of ipecaca (Wormwood), pig skin, bunny puffs, slurper pelts.",
    "Fuelweaver can’t use bone cage near a fuelled shadow thurible on the ground.",
    "You can have both ice bream and scorching sunfish in your inventory and not worry about temperature.",
    "Resources you get back from using a deconstruction staff is proportional to the durability of the item, including refuellable ones, so make sure to refuel them.",
    "Wobyportation: Place meat effigy where you want to teleport later, then place items in woby and chester (eyebone inside woby) and unalive yourself to teleport.",
    "The little kitties from year of the catcoon can turn on cawnival lights if they choose to randomly play with them.",
    "Marroters can collect many things including: kelp, grass (geckos), twig (twiggy trees), minerals (meteor field).",
    "Willow can burn Bearger for him to harvest clumped up trees in panic.",
    "Glowberry can be fed to beefalo, captured rabbits, player pets or eyemask (even if not worn) for light.",
    "Woodie's treeguard idols can spawn treeguards by just using them as fuel for ice flingomatics. And idols can be used by all characters.",
    "Banana shake is great sanity in ruins: 2 banana and 2 filler (twig, nigthmare fuel, boneshard). Spicy chilli as well for health.",
    "Eels are a great way to farm bulk gold at 5 gold each to Pig King, and 2x eels with 2x monster meat can cook surf and turf in the ruins.",
    "Wigfrid can eat treats like Taffy, Jellybeans, Banana Daiquiri, Icecream, Volt goat jelly, Soothing tea, and Sanguine Mix.",
    "Activated umbralla on the grounda provides -25 sanity/min, or 12.5 sanity/min with bee queen crown. You can stack as many as you want on ground.",
    "You can save durability on a thule club by hitting a crawling horror 5 times, and punching for the last hit.",
    "You can force Slurtle mound to spawn a Snurtle for its armor by burning and extinguishing the mound (e.g. with watering can) until a snurtle spawns.",
    "Lightning protection (rain coat, eyebrella etc.) also makes you immune to moon gleam's shock.",
    "Willow with Controlled Fire perk can ignite an object twice for applying normal, spreading fire to it.",
    "You can convert 1 pinecone or birchnut into 1 twig by planting it and digging it up with a shovel in a pinch.",
    "Terrarium gives light even when inactive and can prevent Charlie attacks if dropped at your feet.",
    "If you stand on the oasis lake when summer starts the oasis lake will not fill up with water, nor activate the sandstorm and Antlion.",
    "Sandstorm, Antlion and Wildfires cannot occur during rain. Wickerbottom's rain book is perfect for summer.",
}
