STRINGS = GLOBAL.STRINGS

STRINGS.FORBIDDEN_LOADINGTIPS = {
    "Winbot places items on the go inside dropped backpacks as Winona.",
    "Winbot scares grass geckos like chester, and also picks up the grass.",
    "Cookie cutters are distracted towards wood items in the water (log suits, woodie hats, etc).",
    "Dark swords and shadow monsters like shadow merms keep gestlats away on lunar island.",
    "Moles dont steal socketed moonlens, so you can mark wormholes for everyone to see.",
    "Webber switcherdoodles are non-spoil -10 sanity for other characters that need it, like Willow.",
    "Non-spoil Eyemask restoration: Kitcshy idols (Woodie), Syrup of ipecaca (Wormwood), pig skin, bunny puffs, slurper pelts.",
    "Fuelweaver can’t use bone cage near a fuelled shadow thurible on the ground.",
    "You can have both ice bream and scorching sunfish in your inventory and not worry about temperature.",
    "Resources you get back from using a deconstruction staff is proportional to the durability of the item, including refuellable ones, so make sure to refuel them.",
    "Wobyportation: Place meat effigy where you want to teleport later, then place items in woby and chester (eyebone inside woby) and unalive yourself to teleport.",
    "The little kitties from year of the catcoon can turn on cawnival lights if they choose to randomly play with them.",
    "Marroters can collect many things including: kelp, grass (geckos), twig (twiggy trees), minerals (meteor field).",
    "Willow can burn Bearger for him to harvest clumped up trees in panic.",
    "Glowberry can be fed to beefalo, captured rabbits, player pets or eyemask (even if not worn) for light.",
    "Woodie's treeguard idols can spawn treeguards by just using them as fuel for ice flingomatics. And idols can be used by all characters.",
    "Banana shake is great sanity in ruins: 2 banana and 2 filler (twig, nigthmare fuel, boneshard). Spicy chilli as well for health.",
    "Eels are a great way to farm bulk gold at 5 gold each to Pig King, and 2x eels with 2x monster meat can cook surf and turf in the ruins.",
    "Wigfrid can eat treats like Taffy, Jellybeans, Banana Daiquiri, Icecream, Volt goat jelly, Soothing tea, and Sanguine Mix.",
    "Activated umbralla on the grounda provides -25 sanity/min, or 12.5 sanity/min with bee queen crown. You can stack as many as you want on ground.",
    "You can save durability on a thule club by hitting a crawling horror 5 times, and punching for the last hit.",
    "You can force Slurtle mound to spawn a Snurtle for its armor by burning and extinguishing the mound (e.g. with watering can) until a snurtle spawns.",
    "Lightning protection (rain coat, eyebrella etc.) also makes you immune to moon gleam's shock.",
    "Willow with Controlled Fire perk can ignite an object twice for applying normal, spreading fire to it.",
    "You can convert 1 pinecone or birchnut into 1 twig by planting it and digging it up with a shovel in a pinch.",
    "Terrarium gives light even when inactive and can prevent Charlie attacks if dropped at your feet.",
    "If you stand on the oasis lake when summer starts the oasis lake will not fill up with water, nor activate the sandstorm and Antlion.",
    "Sandstorm, Antlion and Wildfires cannot occur during rain. Wickerbottom's rain book is perfect for summer.",
    "Many creatures will chase you for 33% longer distance during spring.",
    "Spider Nests will have their guard spawning radius increased by 33% in spring. Meaning guards can spawn when attacking spiders outside the webbing.",
    "Fire has a smaller damage radius during spring, allowing you to attack burning mobs without taking damage.",
    "The Antlion fight can be started on the final moments of summer for a sandstorm free fight.",
    "Wickerbottom's lunar book can reset moon cycle for rushing fuelweaver earlier. If you read it day 6, new moon will be 10 days later on day 16 instead of standard day 21.",
    "Enlightened crown Gestalts and Wormwood's Bramble Husk Specialist insight will trigger even while attacking from a ridden beefalo.",
    "Wormwood bramble husk armor negates getting damaged by picking cactus or spiky twigs.",
    "Mini tentacles can be easily killed by Fugu hutch, bramble husks, and Abigail.",
    "Players on non-pvp worlds can be damaged by cannonballs and freezing waterballoons.",
    "Baconegg and monster lasagna have same priority, so you can gamble for a 50/50 chance with two monstermeat and two eggs in crockpot.",
    "Spicy chilli and monster lasagna have same priority, so you can gamble for a 50/50 chance with two monstermeat and two veggies like lichen in crockpot.",
    "You can examine a crockpot to for how long it takes to cook. You can use this to tell if a dish is gonna turn into a Monster Lasagna (short cooktime) vs Baconegg (long cooktime)",
    "You can open 20 full stacks of stone fruit with one gunpowder OR one slurtle slime explosion.",
    "Steam has a notes tab in the Shift+Tab overlay. You can note down boss spawns for instance or anything you want.",
    "Fish Cordon Bleu wetness immunity works for Acid Rain HP and food spoiling effects too.",
    "Burned signs give back 1 board when hammered, and can be recrafted with 1 board. You can keep a sign pre-prototyped for continuous light and heat.",
    "Skittersquids can be caught below docks for a small permanent light.",
    "You can bring the item held in your mouse into caves by dropping it near cave, clicking the entrance, keeping click pressed, and pressing space after.",
    "Wicker Everything Encyclopedia book also gives tier 1 magic tier and 1 think tank tier bonus level of knowledge.",
    "Fish summoned from Angler's Survival Guide is more likely to spawn on the northeast direction.",
    "Hiveless bees propagate flowers after pollinating 6 different flowers, evil flowers too.",
    "Bee boxes can work in middle of ocean by spawning flowers on a boat by dropping a bee that polinated 6 flowers.",
    "You can set a mushgnome on fire to easily produce tons of ash.",
    "Living logs dont burn if you kill a treeguard or a mushgnome while on fire, only smolder.",
    "Moleworms can be given to a wormhole to create a new burrow on the other end.",
    "To get early specific seeds to rush farming, you can befriend and trade with catcoons.",
    "Catcoons can be brought on a boat to trade for items during a long sail.",
    "During moonstorm event you socket and unsocket the starcaller over and over to spawn more mobs for a lot of pig skin and monstermeat.",
    "Smallbirds can be fed berries, seeds, meat, rot to grow into a new tallbird and egg nest.",
    "You can relocate a tallbirds by burning their nests and getting chased to a new location.",
    "If you adopt a natural teenbird, you can avoid the waiting time from growing a tallbird from an egg.",
    "Woodie beaver form can sail really fast using pats of its tail."
}
