STRINGS = GLOBAL.STRINGS

STRINGS.FORBIDDEN_LOADINGTIPS = {
    "Winbot places items on the go inside dropped backpacks as Winona.",
    "Winbot scares grass geckos like chester, and also picks up the grass.",
    "Cookie cutters are distracted towards wood items in the water (log suits, woodie hats, etc).",
    "Dark swords and shadow monsters like shadow merms keep gestlats away on lunar island.",
    "Moles dont steal socketed moonlens, so you can mark wormholes for everyone to see.",
    "Webber switcherdoodles are non-spoil -10 sanity for other characters that need it, like Willow.",
    "Non-spoil Eyemask restoration: Kitcshy idols (Woodie), Syrup of ipecaca (Wormwood), pig skin, bunny puffs, slurper pelts.",
    "Fuelweaver can’t use bone cage near a fuelled shadow thurible on the ground.",
    "You can have both ice bream and scorching sunfish in your inventory and not worry about temperature.",
    "Resources you get back from using a deconstruction staff is proportional to the durability of the item, including refuellable ones, so make sure to refuel them.",
    "Wobyportation: Place meat effigy where you want to teleport later, then place items in woby and chester (eyebone inside woby) and unalive yourself to teleport.",
    "The little kitties from year of the catcoon can turn on cawnival lights if they choose to randomly play with them.",
    "Marroters can collect many things including: kelp, grass (geckos), twig (twiggy trees), minerals (meteor field).",
    "Willow can burn Bearger for him to harvest clumped up trees in panic.",
    "Glowberry can be fed to beefalo, captured rabbits, player pets or eyemask (even if not worn) for light.",
    "Woodie's treeguard idols can spawn treeguards by just using them as fuel for ice flingomatics. And idols can be used by all characters.",
    "Banana shake is great sanity in ruins: 2 banana and 2 filler (twig, nigthmare fuel, boneshard). Spicy chilli as well for health.",
    "Eels are a great way to farm bulk gold at 5 gold each to Pig King, and 2x eels with 2x monster meat can cook surf and turf in the ruins.",
    "Wigfrid can eat treats like Taffy, Jellybeans, Banana Daiquiri, Icecream, Volt goat jelly, Soothing tea, and Sanguine Mix.",
    "Activated umbralla on the grounda provides -25 sanity/min, or 12.5 sanity/min with bee queen crown. You can stack as many as you want on ground.",
    "You can save durability on a thule club by hitting a crawling horror 5 times, and punching for the last hit.",
    "You can force Slurtle mound to spawn a Snurtle for its armor by burning and extinguishing the mound (e.g. with watering can) until a snurtle spawns.",
    "Lightning protection (rain coat, eyebrella etc.) also makes you immune to moon gleam's shock.",
    "Willow with Controlled Fire perk can ignite an object twice for applying normal, spreading fire to it.",
    "You can convert 1 pinecone or birchnut into 1 twig by planting it and digging it up with a shovel in a pinch.",
    "Terrarium gives light even when inactive and can prevent Charlie attacks if dropped at your feet.",
    "If you stand on the oasis lake when summer starts the oasis lake will not fill up with water, nor activate the sandstorm and Antlion.",
    "Sandstorm, Antlion and Wildfires cannot occur during rain. Wickerbottom's rain book is perfect for summer.",
    "Many creatures will chase you for 33% longer distance during spring.",
    "Spider Nests will have their guard spawning radius increased by 33% in spring. Meaning guards can spawn when attacking spiders outside the webbing.",
    "Fire has a smaller damage radius during spring, allowing you to attack burning mobs without taking damage.",
    "The Antlion fight can be started on the final moments of summer for a sandstorm free fight.",
    "Wickerbottom's lunar book can reset moon cycle for rushing fuelweaver earlier. If you read it day 6, new moon will be 10 days later on day 16 instead of standard day 21.",
    "Enlightened crown Gestalts and Wormwood's Bramble Husk Specialist insight will trigger even while attacking from a ridden beefalo.",
    "Wormwood bramble husk armor negates getting damaged by picking cactus or spiky twigs.",
    "Mini tentacles can be easily killed by Fugu hutch, bramble husks, and Abigail.",
    "Players on non-pvp worlds can be damaged by cannonballs and freezing waterballoons.",
    "Baconegg and monster lasagna have same priority, so you can gamble for a 50/50 chance with two monstermeat and two eggs in crockpot.",
    "Spicy chilli and monster lasagna have same priority, so you can gamble for a 50/50 chance with two monstermeat and two veggies like lichen in crockpot.",
    "You can examine a crockpot to for how long it takes to cook. You can use this to tell if a dish is gonna turn into a Monster Lasagna (short cooktime) vs Baconegg (long cooktime)",
    "You can open 20 full stacks of stone fruit with one gunpowder OR one slurtle slime explosion.",
    "Steam has a notes tab in the Shift+Tab overlay. You can note down boss spawns for instance or anything you want.",
    "Fish Cordon Bleu wetness immunity works for Acid Rain HP and food spoiling effects too.",
    "Burned signs give back 1 board when hammered, and can be recrafted with 1 board. You can keep a sign pre-prototyped for continuous light and heat.",
    "Skittersquids can be caught below docks for a small permanent light.",
    "You can bring the item held in your mouse into caves by dropping it near cave, clicking the entrance, keeping click pressed, and pressing space after.",
    "Wicker Everything Encyclopedia book also gives tier 1 magic tier and 1 think tank tier bonus level of knowledge.",
    "Fish summoned from Angler's Survival Guide is more likely to spawn on the northeast direction.",
    "Hiveless bees propagate flowers after pollinating 6 different flowers, evil flowers too.",
    "Bee boxes can work in middle of ocean by spawning flowers on a boat by dropping a bee that polinated 6 flowers.",
    "You can set a mushgnome on fire to easily produce tons of ash.",
    "Living logs dont burn if you kill a treeguard or a mushgnome while on fire, only smolder.",
    "Moleworms can be given to a wormhole to create a new burrow on the other end.",
    "To get early specific seeds to rush farming, you can befriend and trade with catcoons.",
    "Catcoons can be brought on a boat to trade for items during a long sail.",
    "During moonstorm event you socket and unsocket the starcaller over and over to spawn more mobs for a lot of pig skin and monstermeat.",
    "Smallbirds can be fed berries, seeds, meat, rot to grow into a new tallbird and egg nest.",
    "You can relocate a tallbirds by burning their nests and getting chased to a new location.",
    "If you adopt a natural teenbird, you can avoid the waiting time from growing a tallbird from an egg.",
    "Woodie beaver form can sail really fast using pats of its tail.",
    "When an earthquake occurs in the cave, monkeys without hate targets will discard all items and flee back to the monkey's nest.",
    "Greater gestalts hate dark items, and will hit you like a truck. Wearing celestial crown removes this, even if you wear dark items.",
    "Giant pillars prevent rockfall during toadstool 3rd stage. Woodie hardwood hat prevent falling rock damage too.",
    "Two pillars can block enemies from advancing, taking 50 walking hits from bosses to break (e.g. toadstool and fuelweaver).",
    "You can rob year of the bunnymen bunnies from their pillows by spawning them near moose goose and letting him honk at them.",
    "Festive lights give light forever inside Mushlights, Glowcaps, Hutch, even if they are at 0% fuel.",
    "Enlightened shards make glowing spoilables last forever inside light containers.",
    "If you select “Plus” when generating the world you get a chest for two dragonfruits for wormwood early saladmanders.",
    "You can tell if a glowberry is a depth worm if it is wet while the world is dry. Depth worms are always wet. You can also hover a torch over it, as Worms don’t have the “Burn” prompt.",
    "Woodie and Wurt can tell if a glowberry is a depth worm based on its examine text.",
    "Powder monkeys don’t come out of their houses during winter unless they are broken or burning.",
    "Weekly gift drops happen even if the game is on pause.",
    "Mighty Wolfgang opens two stonefruits in a stack at once and critically striking it will open the entire stack.,
    "A bramble husk wearing target dummy can be activated for area damage by poop slingshots, pillows, ice staff, and brightshade staff.",
    "Dragonfly home location can be reset by putting her to sleep. If you bring her far enough, she spits lava on ground or at the closest pond.",
    "Moleworms can store a ton of turf inside their burrow.",
    "Walter can use poop pellets as fire fuel for increased effectiveness.",
    "Character ghosts can haunt Wendy’s vigor mortis elixir for 3 second speed boost.",
    "Woodie’s idols and winter’s feast eggnog don’t spoil and can be fed to a bird in a cage for an egg.",
    "You can make a reliable longterm Malbatross spawn by building docks towards a spawner.",
    "Beequeen crown can be deconstructed for 4 honeycombs for bundlewraps, when at full durability.",
    "Volt goats can be electrified near tree guards with an electric dart. Volt goat dies in the process, and Treeguards die eventually.",
    "You can mark wormholes, cave exits and tentacles with turf, signs or statues to hint where they lead to.",
    "To get rid of monkey curse, die to a lureplant, and it will eat your cursed trinkets. Lureplants digest an item every 20 seconds.",
    "Lureplants digest one eatem item every 20 seconds when loaded. One item from a stack at a time.",
    "You can hoe perfectly without any helper client mods by hoeing, planting, and then hoeing near the plant.",
    "In settings you can configure more quickcraft tabs.",
    "Dropped items prevent tentacle spawning from Wicker's tentacle book, so you can make a cheap lattice of twigs instead of placing broken walls.",
    "Shell bells can be hammered for broken shells, which can make shell bumpers to smash into sea stacks and other sea things.",
    "Food inside your Wilson beard is hidden. Bunnymen and marotters dont detect your food.",
    "Wilson transmuting an almost spoiled big meat creates two fresh morsels.",
    "To get a ton of rotten eggs and rot lategame, capture misshapen birds during wagstaff event and place in birdcage. They give rotten eggs and rot instead of seeds.",
    "Cookie cutters cannot eat docks. You can build docks towards a cookie cutter salt area.",
    "Relocated sea stacks yield barnacles which are the best source of bulk eggs at 3 per harvest. You can build boats towards them and also setup fishing trawlers.",
    "Bacon and eggs needs more than 1 meat, and barnacles are 0.25 meat. So you can cheaply make a baconegg with 1 monstermeat and 3 barnacles (2 converted to eggs)",
    "WX circuits lose all charge when removed UNLESS you become wet or starve to make the circuit inactive and safely remove without waiting for charge to rebuild.",
    "Rowing too fast on a boat increases your wetness. Can be used for Wurt wetness skill tree perk, WX deactivating a circuit or WX making ice with refrigeration circuit.",
    "WX can heat his thermal stones until they become incandescent and glowing by using two thermal circuits",
    "You can make 1 water balloon per mosquito sack by hovering it over a pond and clicking for filling it. No ice required, but less balloons per sack.",
    "Bunnymen can farm and protect from many mobs without eating meat: Batilisks, spiders, mosquitos, and bee stingers for ash.",
    "Sleeping in a bed roll prevents Charlie hitting you in the dark. If you are caught without twigs and can’t craft a torch, you can craft a straw roll using only grass.",
    "Woodie beaver form can farm papyrus by hammering stagehand. Around 8 blueprints per transformation duration.",
    "Tail o’ three cats forces snurtles and rock lobsters out of their shield and prevents them from going back into them.",
    "You can extend Webber spider wars by upgrading and downgrading nests from T2 to T3 and back while the war is ongoing.",
    "Spiders give gold: Monster meat -> Egg -> Pig king -> 1x Gold",
    "Changing Fire Pit’s skin with a Clean Sweeper removes shadow hands that are trying to smother the fire from it.",
    "You can collect ocean debris with a fishing hook if you aim the dark spot.",
    "Hounds can be distracted by the firecracker seasonal item, especially the hounds summoned by howling Vargs.",
    "To collect honey, set the bee boxes on fire near an ice flingomatic. The bees will panic and not chase you if you pick their honey.",
    "Haunting a guard's pig torch as a ghost has a chance for respawning the pig guard. Haunting a pig, guard or not, has a chance to turn it into a werepig.",
    "Feeding four monster value food to a pig turns it into a werepig. Werepigs like eating spoilables like petals and lightbulbs on ground. They poop after each time they eat."
}
